version: '3'

services:

  api:
    container_name: api
    restart: always
    build: ./api
    networks:
        - internal_net
    expose:
        - "5000"
    ports:
        - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
        - internal_net
    expose:
        - "80"
    ports:
        - "80:80"
    depends_on:
        - api
  
  test_api:
    container_name: test_api
    restart: always
    build: ./testing
    networks:
        - internal_net
    expose:
        - "8089"
        - "1234"
    ports:
        - "8089:8089"
        - "1234:1234"

networks:
  internal_net: